# 容器的端口号
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8


spring:
  # 热部署
  devtools:
    restart:
      enabled: true
      # 设置重启的目录
      additional-paths: src/main/java
  # mvc的jsp路径
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
    static-path-pattern: /**
  # 编码
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

